# Use root/example as user/password credentials

version: '3.1'

services:

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example

  web-server:
    build: .
      # context: .
      # dockerfile: Dockerfile
    # image: php:5.6-apache
    container_name: web-server
    volumes:
      - ./src:/var/www
    ports:
      - 3000:80

  # nginx:
  #   image: richarvey/nginx-php-fpm:latest
  #   volumes:
  #     - ./src:/var/www/html
  #   ports:
  #     - 3000:80
  #   environment:
  #     WEBROOT: /var/www/html/html/

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./src/html:/usr/share/nginx/html:ro
  #     # - ./default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 3000:80

  # php:
  #   image: php
